version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - ./packages/portal-db/postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - default
  keycloak:
      image: "keycloak/keycloak"
      container_name: keycloak
      command:
        - "start-dev"
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      networks:
        - default
  ui:
    build:
      context: ./packages/portal-ui/
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - default
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart:
      on-failure
    networks:
        - default
